language: python
rvm:
  - 3.6.7
# command to install dependencies
install:
  - pip install miniseq
  - pip install ./
  - pip install pytest-cov
  - pip install coveralls

# command to run tests
script: export PYTHONPATH=. && pytest --cov=minineedle/ tests/

after_success:
- coveralls
